# -*- coding: utf-8 -*-
"""Project_phase3/4.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wjMj1TIjZrtjXvkTuZlZIGuCIo7Pq22M
"""

import os
import csv
import requests
from bs4 import BeautifulSoup

BASE_URL = "http://books.toscrape.com"


def get_soup(url):
    response = requests.get(url)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")


def get_book_rating(book_tag):
    rating_tag = book_tag.find("p", class_="star-rating")
    if rating_tag is None:
        return None

    classes = rating_tag.get("class", [])
    for c in classes:
        if c != "star-rating":
            return c
    return None


def get_book_details(book_relative_url):
    cleaned_relative_url = book_relative_url.replace("../", "")
    if not cleaned_relative_url.startswith("catalogue/"):
        cleaned_relative_url = "catalogue/" + cleaned_relative_url

    book_url = BASE_URL + "/" + cleaned_relative_url
    soup = get_soup(book_url)

    # CATEGORY (breadcrumb)
    breadcrumb = soup.find("ul", class_="breadcrumb")
    category = None
    if breadcrumb:
        li_tags = breadcrumb.find_all("li")
        if len(li_tags) >= 3:
            category = li_tags[2].get_text(strip=True)

    # PRODUCT INFORMATION TABLE
    table = soup.find("table", class_="table table-striped")
    rows = table.find_all("tr")

    product_info = {}
    for row in rows:
        key = row.find("th").get_text(strip=True)
        value = row.find("td").get_text(strip=True)
        product_info[key] = value

    upc = product_info.get("UPC")
    price_excl_tax = product_info.get("Price (excl. tax)")
    price_incl_tax = product_info.get("Price (incl. tax)")
    quantity_available = product_info.get("Availability")

    # PRODUCT DESCRIPTION
    description_tag = soup.find("div", id="product_description")
    if description_tag:
        product_description = description_tag.find_next("p").get_text(strip=True)
    else:
        product_description = None

    return {
        "category": category,
        "product_page_url": book_url,
        "upc": upc,
        "price_excluding_tax": price_excl_tax,
        "price_including_tax": price_incl_tax,
        "quantity_available": quantity_available,
        "product_description": product_description,
    }


# PHASE 4: DOWNLOAD AND SAVE IMAGE FILE
def download_image(image_url, upc):
    os.makedirs("images", exist_ok=True)

    # Sanitize filename using UPC to ensure uniqueness
    filename = f"images/{upc}.jpg"

    # Download and save binary content
    response = requests.get(image_url)
    if response.status_code == 200:
        with open(filename, "wb") as f:
            f.write(response.content)


# PHASE 3: EXTRACT ALL CATEGORY URLS FROM HOMEPAGE
def get_all_categories():
    homepage_url = f"{BASE_URL}/index.html"
    soup = get_soup(homepage_url)

    category_sidebar = soup.find("div", class_="side_categories")
    category_links = category_sidebar.find("ul").find("ul").find_all("a")

    categories = []
    for link in category_links:
        cat_name = link.get_text(strip=True)
        cat_url = BASE_URL + "/" + link.get("href")
        categories.append((cat_name, cat_url))

    return categories


def scrape_category_page(page_url):
    try:
        soup = get_soup(page_url)
    except requests.exceptions.HTTPError as e:
        if e.response.status_code == 404:
            return []
        else:
            raise

    books = []
    book_tags = soup.find_all("article", class_="product_pod")

    for book in book_tags:
        title_tag = book.find("h3").find("a")
        title = title_tag.get("title")

        rating = get_book_rating(book)
        relative_url = title_tag.get("href")

        image_tag = book.find("img")
        image_relative_url = image_tag.get("src").replace("../", "")
        image_url = BASE_URL + "/" + image_relative_url

        details = get_book_details(relative_url)

        # Download the book cover image (Phase 4)
        if details["upc"]:
            download_image(image_url, details["upc"])

        book_data = {
            "product_page_url": details["product_page_url"],
            "universal_product_code": details["upc"],
            "book_title": title,
            "price_including_tax": details["price_including_tax"],
            "price_excluding_tax": details["price_excluding_tax"],
            "quantity_available": details["quantity_available"],
            "product_description": details["product_description"],
            "category": details["category"],
            "review_rating": rating,
            "image_url": image_url,
        }

        books.append(book_data)

    return books


def scrape_category(category_name, category_base_url):
    category_books = []
    page_number = 1

    while True:
        if page_number == 1:
            page_url = category_base_url
        else:
            page_url = category_base_url.replace("index.html", f"page-{page_number}.html")

        books = scrape_category_page(page_url)

        if not books:
            break

        category_books.extend(books)
        page_number += 1

    print(f"Scraped {len(category_books)} books for '{category_name}'")
    return category_books


def save_to_csv(books, category_name):
    os.makedirs("csv_files", exist_ok=True)
    fieldnames = [
        "product_page_url",
        "universal_product_code",
        "book_title",
        "price_including_tax",
        "price_excluding_tax",
        "quantity_available",
        "product_description",
        "category",
        "review_rating",
        "image_url",
    ]

    filename = f"csv_files/{category_name.lower().replace(' ', '_').replace('/', '_')}.csv"

    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(books)

    print(f"CSV saved: {filename}")


# MAIN RUNNER
if __name__ == "__main__":
    print("Extracting categories from homepage...")
    categories = get_all_categories()
    print(f"Found {len(categories)} categories.\n")

    for cat_name, cat_url in categories:
        print(f"--- Processing Category: {cat_name} ---")
        category_books = scrape_category(cat_name, cat_url)
        save_to_csv(category_books, cat_name)
        print()

    print("Phase 3 & 4 complete! All CSV files and cover images saved.")