# -*- coding: utf-8 -*-
"""project_phase2.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lawFvcTzw803qmv0KfYCH9bTFnfyqRc-
"""

import os
import csv
import requests
from bs4 import BeautifulSoup

BASE_URL = "http://books.toscrape.com"


def get_soup(url):
    response = requests.get(url)
    response.raise_for_status()
    return BeautifulSoup(response.text, "html.parser")


def get_book_rating(book_tag):
    rating_tag = book_tag.find("p", class_="star-rating")
    if rating_tag is None:
        return None

    classes = rating_tag.get("class", [])
    for c in classes:
        if c != "star-rating":
            return c
    return None


def get_book_details(book_relative_url):
    # Fix relative URLs coming from category sub-folders (e.g., '../../../a-light-in-the-attic_1000/index.html')
    cleaned_relative_url = book_relative_url.replace("../", "")
    if not cleaned_relative_url.startswith("catalogue/"):
        cleaned_relative_url = "catalogue/" + cleaned_relative_url

    book_url = BASE_URL + "/" + cleaned_relative_url
    soup = get_soup(book_url)

    # CATEGORY (breadcrumb)
    breadcrumb = soup.find("ul", class_="breadcrumb")
    category = None
    if breadcrumb:
        li_tags = breadcrumb.find_all("li")
        if len(li_tags) >= 3:
            category = li_tags[2].get_text(strip=True)

    # PRODUCT INFORMATION TABLE
    table = soup.find("table", class_="table table-striped")
    rows = table.find_all("tr")

    product_info = {}
    for row in rows:
        key = row.find("th").get_text(strip=True)
        value = row.find("td").get_text(strip=True)
        product_info[key] = value

    upc = product_info.get("UPC")
    price_excl_tax = product_info.get("Price (excl. tax)")
    price_incl_tax = product_info.get("Price (incl. tax)")
    quantity_available = product_info.get("Availability")

    # PRODUCT DESCRIPTION
    description_tag = soup.find("div", id="product_description")
    if description_tag:
        product_description = description_tag.find_next("p").get_text(strip=True)
    else:
        product_description = None

    return {
        "category": category,
        "product_page_url": book_url,
        "upc": upc,
        "price_excluding_tax": price_excl_tax,
        "price_including_tax": price_incl_tax,
        "quantity_available": quantity_available,
        "product_description": product_description,
    }


def scrape_category_page(page_url):
    try:
        soup = get_soup(page_url)
    except requests.exceptions.HTTPError as e:
        if e.response.status_code == 404:
            return [], None
        else:
            raise

    # Extract the category name from the main header
    category_header = soup.find("div", class_="page-header")
    category_name = category_header.find("h1").get_text(strip=True) if category_header else "category"

    books = []
    book_tags = soup.find_all("article", class_="product_pod")

    for book in book_tags:
        title_tag = book.find("h3").find("a")
        title = title_tag.get("title")

        rating = get_book_rating(book)
        relative_url = title_tag.get("href")

        image_tag = book.find("img")
        image_relative_url = image_tag.get("src").replace("../", "")
        image_url = BASE_URL + "/" + image_relative_url

        details = get_book_details(relative_url)

        book_data = {
            "product_page_url": details["product_page_url"],
            "universal_product_code": details["upc"],
            "book_title": title,
            "price_including_tax": details["price_including_tax"],
            "price_excluding_tax": details["price_excluding_tax"],
            "quantity_available": details["quantity_available"],
            "product_description": details["product_description"],
            "category": details["category"],
            "review_rating": rating,
            "image_url": image_url,
        }

        books.append(book_data)

    return books, category_name


def scrape_single_category(category_base_url):
    category_books = []
    page_number = 1
    category_name = "category"

    while True:
        if page_number == 1:
            page_url = category_base_url
        else:
            # Replaces index.html with page-X.html for paginated category pages
            page_url = category_base_url.replace("index.html", f"page-{page_number}.html")

        print(f"Scraping {page_url}...")
        books, current_category_name = scrape_category_page(page_url)

        if not books:
            break

        if current_category_name:
            category_name = current_category_name

        category_books.extend(books)
        page_number += 1

    print(f"Total books scraped for '{category_name}': {len(category_books)}")
    return category_books, category_name


def save_to_csv(books, category_name):
    fieldnames = [
        "product_page_url",
        "universal_product_code",
        "book_title",
        "price_including_tax",
        "price_excluding_tax",
        "quantity_available",
        "product_description",
        "category",
        "review_rating",
        "image_url",
    ]

    filename = f"{category_name.lower().replace(' ', '_')}.csv"

    with open(filename, "w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(books)

    print(f"CSV saved: {filename}")


if __name__ == "__main__":
    # Example: Mystery Category URL
    mystery_url = "http://books.toscrape.com/catalogue/category/books/mystery_3/index.html"

    books, category_name = scrape_single_category(mystery_url)
    save_to_csv(books, category_name)